version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio-postgres
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio_user -d portfolio_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
# Optional: pgAdmin for database management
# Uncomment the section below if you want a web-based database interface

# pgadmin:
#   image: dpage/pgadmin4:latest
#   container_name: portfolio-pgadmin
#   environment:
#     PGADMIN_DEFAULT_EMAIL: admin@portfolio.com
#     PGADMIN_DEFAULT_PASSWORD: admin
#   ports:
#     - "8080:80"
#   depends_on:
#     - postgres
